"""Alembic 迁移 — keywords 增 layer/source/lbs_tags，enterprises 增 raw_inputs。"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54497d69f74b'
down_revision: Union[str, None] = '55c56e6e6c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('raw_inputs', sa.Text(), nullable=True))
    op.add_column('keywords', sa.Column('layer', sa.String(length=20), nullable=True))
    op.add_column('keywords', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('keywords', sa.Column('lbs_tags', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_keywords_layer'), 'keywords', ['layer'], unique=False)
    op.create_index(op.f('ix_keywords_source'), 'keywords', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_source'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_layer'), table_name='keywords')
    op.drop_column('keywords', 'lbs_tags')
    op.drop_column('keywords', 'source')
    op.drop_column('keywords', 'layer')
    op.drop_column('enterprises', 'raw_inputs')
    # ### end Alembic commands ###
