"""initial_schema_v2

Revision ID: ac5a7237aec7
Revises: 
Create Date: 2026-07-07 12:06:24.887474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac5a7237aec7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('industry_pack', sa.String(length=50), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('kb_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enterprises'))
    )
    op.create_index(op.f('ix_enterprises_created_at'), 'enterprises', ['created_at'], unique=False)
    op.create_index(op.f('ix_enterprises_id'), 'enterprises', ['id'], unique=False)
    op.create_index(op.f('ix_enterprises_industry'), 'enterprises', ['industry'], unique=False)
    op.create_index(op.f('ix_enterprises_industry_pack'), 'enterprises', ['industry_pack'], unique=False)
    op.create_index(op.f('ix_enterprises_status'), 'enterprises', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions'))
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission'), 'role_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('target_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('adapter', sa.String(length=100), nullable=True),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_engines'))
    )
    op.create_index(op.f('ix_target_engines_code'), 'target_engines', ['code'], unique=True)
    op.create_index(op.f('ix_target_engines_id'), 'target_engines', ['id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('graph_name', sa.String(length=100), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gate_status', sa.String(length=30), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_agent_tasks_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tasks'))
    )
    op.create_index(op.f('ix_agent_tasks_celery_task_id'), 'agent_tasks', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_created_at'), 'agent_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_enterprise_id'), 'agent_tasks', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_gate_status'), 'agent_tasks', ['gate_status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_graph_name'), 'agent_tasks', ['graph_name'], unique=False)
    op.create_index(op.f('ix_agent_tasks_id'), 'agent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_task_type'), 'agent_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_agent_tasks_trace_id'), 'agent_tasks', ['trace_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('differentiator', sa.Text(), nullable=True),
    sa.Column('slogan', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_brands_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_created_at'), 'brands', ['created_at'], unique=False)
    op.create_index(op.f('ix_brands_enterprise_id'), 'brands', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('faiss_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=True),
    sa.Column('vector_count', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_built_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_faiss_indexes_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faiss_indexes'))
    )
    op.create_index(op.f('ix_faiss_indexes_created_at'), 'faiss_indexes', ['created_at'], unique=False)
    op.create_index(op.f('ix_faiss_indexes_enterprise_id'), 'faiss_indexes', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_faiss_indexes_id'), 'faiss_indexes', ['id'], unique=False)
    op.create_index(op.f('ix_faiss_indexes_index_name'), 'faiss_indexes', ['index_name'], unique=False)
    op.create_index(op.f('ix_faiss_indexes_index_type'), 'faiss_indexes', ['index_type'], unique=False)
    op.create_index(op.f('ix_faiss_indexes_status'), 'faiss_indexes', ['status'], unique=False)
    op.create_table('kb_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_kb_facts_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_facts'))
    )
    op.create_index(op.f('ix_kb_facts_category'), 'kb_facts', ['category'], unique=False)
    op.create_index(op.f('ix_kb_facts_created_at'), 'kb_facts', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_facts_enterprise_id'), 'kb_facts', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_kb_facts_id'), 'kb_facts', ['id'], unique=False)
    op.create_index(op.f('ix_kb_facts_source_type'), 'kb_facts', ['source_type'], unique=False)
    op.create_index(op.f('ix_kb_facts_verified'), 'kb_facts', ['verified'], unique=False)
    op.create_table('kb_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('fact_refs', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_kb_faqs_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_faqs'))
    )
    op.create_index(op.f('ix_kb_faqs_category'), 'kb_faqs', ['category'], unique=False)
    op.create_index(op.f('ix_kb_faqs_created_at'), 'kb_faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_faqs_enterprise_id'), 'kb_faqs', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_kb_faqs_id'), 'kb_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_kb_faqs_source'), 'kb_faqs', ['source'], unique=False)
    op.create_index(op.f('ix_kb_faqs_status'), 'kb_faqs', ['status'], unique=False)
    op.create_index(op.f('ix_kb_faqs_verified'), 'kb_faqs', ['verified'], unique=False)
    op.create_table('kb_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('fact_refs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_kb_signals_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_signals'))
    )
    op.create_index(op.f('ix_kb_signals_created_at'), 'kb_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_signals_enterprise_id'), 'kb_signals', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_kb_signals_id'), 'kb_signals', ['id'], unique=False)
    op.create_index(op.f('ix_kb_signals_signal_type'), 'kb_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_kb_signals_status'), 'kb_signals', ['status'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('keyword_type', sa.String(length=30), nullable=True),
    sa.Column('pool_hint', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pain_cluster_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_keywords_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords'))
    )
    op.create_index(op.f('ix_keywords_created_at'), 'keywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_keywords_enterprise_id'), 'keywords', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword_type'), 'keywords', ['keyword_type'], unique=False)
    op.create_index(op.f('ix_keywords_phrase'), 'keywords', ['phrase'], unique=False)
    op.create_index(op.f('ix_keywords_pool_hint'), 'keywords', ['pool_hint'], unique=False)
    op.create_index(op.f('ix_keywords_status'), 'keywords', ['status'], unique=False)
    op.create_table('monitor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('target_engines', sa.JSON(), nullable=True),
    sa.Column('core_prompts', sa.JSON(), nullable=True),
    sa.Column('probe_prompts', sa.JSON(), nullable=True),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_monitor_profiles_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_profiles'))
    )
    op.create_index(op.f('ix_monitor_profiles_created_at'), 'monitor_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitor_profiles_enterprise_id'), 'monitor_profiles', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_monitor_profiles_id'), 'monitor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_profiles_is_active'), 'monitor_profiles', ['is_active'], unique=False)
    op.create_table('outcome_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('snapshot_type', sa.String(length=30), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_outcome_snapshots_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome_snapshots'))
    )
    op.create_index(op.f('ix_outcome_snapshots_created_at'), 'outcome_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_outcome_snapshots_enterprise_id'), 'outcome_snapshots', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_outcome_snapshots_id'), 'outcome_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_outcome_snapshots_period'), 'outcome_snapshots', ['period'], unique=False)
    op.create_index(op.f('ix_outcome_snapshots_period_start'), 'outcome_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_outcome_snapshots_snapshot_type'), 'outcome_snapshots', ['snapshot_type'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('skill', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('target_engines', sa.JSON(), nullable=True),
    sa.Column('persona_ref', sa.JSON(), nullable=True),
    sa.Column('competitor_ref', sa.JSON(), nullable=True),
    sa.Column('fact_refs', sa.JSON(), nullable=True),
    sa.Column('gap_analysis', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_scenarios_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_channel'), 'scenarios', ['channel'], unique=False)
    op.create_index(op.f('ix_scenarios_created_at'), 'scenarios', ['created_at'], unique=False)
    op.create_index(op.f('ix_scenarios_enterprise_id'), 'scenarios', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_skill'), 'scenarios', ['skill'], unique=False)
    op.create_index(op.f('ix_scenarios_status'), 'scenarios', ['status'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price_hint', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_services_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_enterprise_id'), 'services', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('business_hours', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_stores_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    op.create_index(op.f('ix_stores_city'), 'stores', ['city'], unique=False)
    op.create_index(op.f('ix_stores_created_at'), 'stores', ['created_at'], unique=False)
    op.create_index(op.f('ix_stores_district'), 'stores', ['district'], unique=False)
    op.create_index(op.f('ix_stores_enterprise_id'), 'stores', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_is_primary'), 'stores', ['is_primary'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_users_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_enterprise_id'), 'users', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_task_id', sa.Integer(), nullable=True),
    sa.Column('graph_name', sa.String(length=100), nullable=True),
    sa.Column('step_idx', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('langsmith_run_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], name=op.f('fk_agent_traces_agent_task_id_agent_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_agent_traces_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_traces'))
    )
    op.create_index(op.f('ix_agent_traces_agent_task_id'), 'agent_traces', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_created_at'), 'agent_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_traces_enterprise_id'), 'agent_traces', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_graph_name'), 'agent_traces', ['graph_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_traces_langsmith_run_id'), 'agent_traces', ['langsmith_run_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_step_idx'), 'agent_traces', ['step_idx'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('skill', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('fact_refs', sa.JSON(), nullable=True),
    sa.Column('fact_verify_pass', sa.Boolean(), nullable=True),
    sa.Column('fact_verify_report', sa.JSON(), nullable=True),
    sa.Column('compliance_pass', sa.Boolean(), nullable=True),
    sa.Column('compliance_report', sa.JSON(), nullable=True),
    sa.Column('machine_review_pass', sa.Boolean(), nullable=True),
    sa.Column('human_review_status', sa.String(length=20), nullable=True),
    sa.Column('human_review_note', sa.Text(), nullable=True),
    sa.Column('human_review_by', sa.Integer(), nullable=True),
    sa.Column('human_review_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_content_assets_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['human_review_by'], ['users.id'], name=op.f('fk_content_assets_human_review_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_content_assets_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_assets'))
    )
    op.create_index(op.f('ix_content_assets_channel'), 'content_assets', ['channel'], unique=False)
    op.create_index(op.f('ix_content_assets_created_at'), 'content_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_assets_enterprise_id'), 'content_assets', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_content_assets_human_review_by'), 'content_assets', ['human_review_by'], unique=False)
    op.create_index(op.f('ix_content_assets_human_review_status'), 'content_assets', ['human_review_status'], unique=False)
    op.create_index(op.f('ix_content_assets_id'), 'content_assets', ['id'], unique=False)
    op.create_index(op.f('ix_content_assets_scenario_id'), 'content_assets', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_content_assets_skill'), 'content_assets', ['skill'], unique=False)
    op.create_index(op.f('ix_content_assets_status'), 'content_assets', ['status'], unique=False)
    op.create_table('monitor_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('pool_type', sa.String(length=20), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('mentioned', sa.Boolean(), nullable=True),
    sa.Column('mention_snippet', sa.Text(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('competitor_mentions', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_monitor_results_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['monitor_profiles.id'], name=op.f('fk_monitor_results_profile_id_monitor_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_monitor_results_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_results'))
    )
    op.create_index(op.f('ix_monitor_results_batch_no'), 'monitor_results', ['batch_no'], unique=False)
    op.create_index(op.f('ix_monitor_results_created_at'), 'monitor_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitor_results_engine'), 'monitor_results', ['engine'], unique=False)
    op.create_index(op.f('ix_monitor_results_enterprise_id'), 'monitor_results', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_monitor_results_id'), 'monitor_results', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_results_pool_type'), 'monitor_results', ['pool_type'], unique=False)
    op.create_index(op.f('ix_monitor_results_profile_id'), 'monitor_results', ['profile_id'], unique=False)
    op.create_index(op.f('ix_monitor_results_run_at'), 'monitor_results', ['run_at'], unique=False)
    op.create_index(op.f('ix_monitor_results_scenario_id'), 'monitor_results', ['scenario_id'], unique=False)
    op.create_table('source_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('platform_stats', sa.JSON(), nullable=True),
    sa.Column('map_gap', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('agent_task_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], name=op.f('fk_source_diagnoses_agent_task_id_agent_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_source_diagnoses_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_diagnoses'))
    )
    op.create_index(op.f('ix_source_diagnoses_agent_task_id'), 'source_diagnoses', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_batch_no'), 'source_diagnoses', ['batch_no'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_created_at'), 'source_diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_engine'), 'source_diagnoses', ['engine'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_enterprise_id'), 'source_diagnoses', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_id'), 'source_diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_source_diagnoses_status'), 'source_diagnoses', ['status'], unique=False)
    op.create_table('strategy_pack_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_strategy_pack_drafts_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['agent_tasks.id'], name=op.f('fk_strategy_pack_drafts_job_id_agent_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_pack_drafts'))
    )
    op.create_index(op.f('ix_strategy_pack_drafts_created_at'), 'strategy_pack_drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_pack_drafts_enterprise_id'), 'strategy_pack_drafts', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_strategy_pack_drafts_expires_at'), 'strategy_pack_drafts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_strategy_pack_drafts_id'), 'strategy_pack_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_pack_drafts_job_id'), 'strategy_pack_drafts', ['job_id'], unique=False)
    op.create_index(op.f('ix_strategy_pack_drafts_status'), 'strategy_pack_drafts', ['status'], unique=False)
    op.create_table('approval_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('machine_review_snapshot', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_approval_logs_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_approval_logs_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_logs'))
    )
    op.create_index(op.f('ix_approval_logs_action'), 'approval_logs', ['action'], unique=False)
    op.create_index(op.f('ix_approval_logs_actor_id'), 'approval_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_content_asset_id'), 'approval_logs', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_created_at'), 'approval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_logs_enterprise_id'), 'approval_logs', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_id'), 'approval_logs', ['id'], unique=False)
    op.create_table('hosted_page_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_asset_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_hosted_page_events_content_asset_id_content_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_hosted_page_events_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosted_page_events'))
    )
    op.create_index(op.f('ix_hosted_page_events_content_asset_id'), 'hosted_page_events', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_created_at'), 'hosted_page_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_enterprise_id'), 'hosted_page_events', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_event_at'), 'hosted_page_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_event_type'), 'hosted_page_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_id'), 'hosted_page_events', ['id'], unique=False)
    op.create_index(op.f('ix_hosted_page_events_session_id'), 'hosted_page_events', ['session_id'], unique=False)
    op.create_table('kb_externals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fact_refs', sa.JSON(), nullable=True),
    sa.Column('source_diagnosis_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_kb_externals_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_diagnosis_id'], ['source_diagnoses.id'], name=op.f('fk_kb_externals_source_diagnosis_id_source_diagnoses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_externals'))
    )
    op.create_index(op.f('ix_kb_externals_created_at'), 'kb_externals', ['created_at'], unique=False)
    op.create_index(op.f('ix_kb_externals_enterprise_id'), 'kb_externals', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_kb_externals_id'), 'kb_externals', ['id'], unique=False)
    op.create_index(op.f('ix_kb_externals_source_diagnosis_id'), 'kb_externals', ['source_diagnosis_id'], unique=False)
    op.create_index(op.f('ix_kb_externals_source_platform'), 'kb_externals', ['source_platform'], unique=False)
    op.create_index(op.f('ix_kb_externals_status'), 'kb_externals', ['status'], unique=False)
    op.create_table('publish_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_asset_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('target_url', sa.String(length=1000), nullable=True),
    sa.Column('published_url', sa.String(length=1000), nullable=True),
    sa.Column('published_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fallback_semi', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('utm_content', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_assets.id'], name=op.f('fk_publish_tasks_content_asset_id_content_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_publish_tasks_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publish_tasks'))
    )
    op.create_index(op.f('ix_publish_tasks_channel'), 'publish_tasks', ['channel'], unique=False)
    op.create_index(op.f('ix_publish_tasks_content_asset_id'), 'publish_tasks', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_publish_tasks_created_at'), 'publish_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_publish_tasks_enterprise_id'), 'publish_tasks', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_publish_tasks_id'), 'publish_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_publish_tasks_status'), 'publish_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_publish_tasks_utm_content'), 'publish_tasks', ['utm_content'], unique=False)
    op.create_table('strategy_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('persona', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('scenarios', sa.JSON(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_strategy_packs_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['draft_id'], ['strategy_pack_drafts.id'], name=op.f('fk_strategy_packs_draft_id_strategy_pack_drafts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_strategy_packs_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_packs'))
    )
    op.create_index(op.f('ix_strategy_packs_confirmed_by'), 'strategy_packs', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_strategy_packs_created_at'), 'strategy_packs', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_packs_draft_id'), 'strategy_packs', ['draft_id'], unique=False)
    op.create_index(op.f('ix_strategy_packs_enterprise_id'), 'strategy_packs', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_strategy_packs_id'), 'strategy_packs', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_packs_status'), 'strategy_packs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_packs_status'), table_name='strategy_packs')
    op.drop_index(op.f('ix_strategy_packs_id'), table_name='strategy_packs')
    op.drop_index(op.f('ix_strategy_packs_enterprise_id'), table_name='strategy_packs')
    op.drop_index(op.f('ix_strategy_packs_draft_id'), table_name='strategy_packs')
    op.drop_index(op.f('ix_strategy_packs_created_at'), table_name='strategy_packs')
    op.drop_index(op.f('ix_strategy_packs_confirmed_by'), table_name='strategy_packs')
    op.drop_table('strategy_packs')
    op.drop_index(op.f('ix_publish_tasks_utm_content'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_status'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_id'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_enterprise_id'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_created_at'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_content_asset_id'), table_name='publish_tasks')
    op.drop_index(op.f('ix_publish_tasks_channel'), table_name='publish_tasks')
    op.drop_table('publish_tasks')
    op.drop_index(op.f('ix_kb_externals_status'), table_name='kb_externals')
    op.drop_index(op.f('ix_kb_externals_source_platform'), table_name='kb_externals')
    op.drop_index(op.f('ix_kb_externals_source_diagnosis_id'), table_name='kb_externals')
    op.drop_index(op.f('ix_kb_externals_id'), table_name='kb_externals')
    op.drop_index(op.f('ix_kb_externals_enterprise_id'), table_name='kb_externals')
    op.drop_index(op.f('ix_kb_externals_created_at'), table_name='kb_externals')
    op.drop_table('kb_externals')
    op.drop_index(op.f('ix_hosted_page_events_session_id'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_id'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_event_type'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_event_at'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_enterprise_id'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_created_at'), table_name='hosted_page_events')
    op.drop_index(op.f('ix_hosted_page_events_content_asset_id'), table_name='hosted_page_events')
    op.drop_table('hosted_page_events')
    op.drop_index(op.f('ix_approval_logs_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_enterprise_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_created_at'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_content_asset_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_actor_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_action'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_strategy_pack_drafts_status'), table_name='strategy_pack_drafts')
    op.drop_index(op.f('ix_strategy_pack_drafts_job_id'), table_name='strategy_pack_drafts')
    op.drop_index(op.f('ix_strategy_pack_drafts_id'), table_name='strategy_pack_drafts')
    op.drop_index(op.f('ix_strategy_pack_drafts_expires_at'), table_name='strategy_pack_drafts')
    op.drop_index(op.f('ix_strategy_pack_drafts_enterprise_id'), table_name='strategy_pack_drafts')
    op.drop_index(op.f('ix_strategy_pack_drafts_created_at'), table_name='strategy_pack_drafts')
    op.drop_table('strategy_pack_drafts')
    op.drop_index(op.f('ix_source_diagnoses_status'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_id'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_enterprise_id'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_engine'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_created_at'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_batch_no'), table_name='source_diagnoses')
    op.drop_index(op.f('ix_source_diagnoses_agent_task_id'), table_name='source_diagnoses')
    op.drop_table('source_diagnoses')
    op.drop_index(op.f('ix_monitor_results_scenario_id'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_run_at'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_profile_id'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_pool_type'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_id'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_enterprise_id'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_engine'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_created_at'), table_name='monitor_results')
    op.drop_index(op.f('ix_monitor_results_batch_no'), table_name='monitor_results')
    op.drop_table('monitor_results')
    op.drop_index(op.f('ix_content_assets_status'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_skill'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_scenario_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_human_review_status'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_human_review_by'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_enterprise_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_created_at'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_channel'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_agent_traces_step_idx'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_langsmith_run_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_graph_name'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_enterprise_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_created_at'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_agent_task_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_enterprise_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_is_primary'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_enterprise_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_district'), table_name='stores')
    op.drop_index(op.f('ix_stores_created_at'), table_name='stores')
    op.drop_index(op.f('ix_stores_city'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_enterprise_id'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_scenarios_status'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_skill'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_enterprise_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_created_at'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_channel'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_outcome_snapshots_snapshot_type'), table_name='outcome_snapshots')
    op.drop_index(op.f('ix_outcome_snapshots_period_start'), table_name='outcome_snapshots')
    op.drop_index(op.f('ix_outcome_snapshots_period'), table_name='outcome_snapshots')
    op.drop_index(op.f('ix_outcome_snapshots_id'), table_name='outcome_snapshots')
    op.drop_index(op.f('ix_outcome_snapshots_enterprise_id'), table_name='outcome_snapshots')
    op.drop_index(op.f('ix_outcome_snapshots_created_at'), table_name='outcome_snapshots')
    op.drop_table('outcome_snapshots')
    op.drop_index(op.f('ix_monitor_profiles_is_active'), table_name='monitor_profiles')
    op.drop_index(op.f('ix_monitor_profiles_id'), table_name='monitor_profiles')
    op.drop_index(op.f('ix_monitor_profiles_enterprise_id'), table_name='monitor_profiles')
    op.drop_index(op.f('ix_monitor_profiles_created_at'), table_name='monitor_profiles')
    op.drop_table('monitor_profiles')
    op.drop_index(op.f('ix_keywords_status'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_pool_hint'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_phrase'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword_type'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_enterprise_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_created_at'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_kb_signals_status'), table_name='kb_signals')
    op.drop_index(op.f('ix_kb_signals_signal_type'), table_name='kb_signals')
    op.drop_index(op.f('ix_kb_signals_id'), table_name='kb_signals')
    op.drop_index(op.f('ix_kb_signals_enterprise_id'), table_name='kb_signals')
    op.drop_index(op.f('ix_kb_signals_created_at'), table_name='kb_signals')
    op.drop_table('kb_signals')
    op.drop_index(op.f('ix_kb_faqs_verified'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_status'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_source'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_id'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_enterprise_id'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_created_at'), table_name='kb_faqs')
    op.drop_index(op.f('ix_kb_faqs_category'), table_name='kb_faqs')
    op.drop_table('kb_faqs')
    op.drop_index(op.f('ix_kb_facts_verified'), table_name='kb_facts')
    op.drop_index(op.f('ix_kb_facts_source_type'), table_name='kb_facts')
    op.drop_index(op.f('ix_kb_facts_id'), table_name='kb_facts')
    op.drop_index(op.f('ix_kb_facts_enterprise_id'), table_name='kb_facts')
    op.drop_index(op.f('ix_kb_facts_created_at'), table_name='kb_facts')
    op.drop_index(op.f('ix_kb_facts_category'), table_name='kb_facts')
    op.drop_table('kb_facts')
    op.drop_index(op.f('ix_faiss_indexes_status'), table_name='faiss_indexes')
    op.drop_index(op.f('ix_faiss_indexes_index_type'), table_name='faiss_indexes')
    op.drop_index(op.f('ix_faiss_indexes_index_name'), table_name='faiss_indexes')
    op.drop_index(op.f('ix_faiss_indexes_id'), table_name='faiss_indexes')
    op.drop_index(op.f('ix_faiss_indexes_enterprise_id'), table_name='faiss_indexes')
    op.drop_index(op.f('ix_faiss_indexes_created_at'), table_name='faiss_indexes')
    op.drop_table('faiss_indexes')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_enterprise_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_created_at'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_agent_tasks_trace_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_task_type'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_graph_name'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_gate_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_enterprise_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_created_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_celery_task_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_target_engines_id'), table_name='target_engines')
    op.drop_index(op.f('ix_target_engines_code'), table_name='target_engines')
    op.drop_table('target_engines')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_enterprises_status'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_industry_pack'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_industry'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_id'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_created_at'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
