"""向后兼容：旧代码 `from app.schemas.business import X` 仍可用。"""
from app.schemas.diagnosis import PainPoint, PersonaData, CompetitorItem
from app.schemas.strategy import (
    ScenarioBase,
    ScenarioCreate,
    ScenarioUpdate,
    ScenarioResponse,
    ScenarioListParams,
    ChannelWeight,
    StrategyPackBase,
    StrategyPackCreate,
    StrategyPackUpdate,
    StrategyPackResponse,
    StrategyPackListParams,
)
from app.schemas.content import (
    FactVerifyReport,
    ComplianceReport,
    ContentDraftBase,
    ContentDraftCreate,
    ContentDraftUpdate,
    ContentDraftResponse,
    ContentDraftListParams,
    BulkApproveRequest,
    ApprovalLogResponse,
)
from app.schemas.publish import (
    PublishTaskBase,
    PublishTaskCreate,
    PublishTaskUpdate,
    PublishTaskResponse,
    PublishTaskListParams,
)
from app.schemas.monitor import (
    MonitorResultBase,
    MonitorResultCreate,
    MonitorResultResponse,
    MonitorResultListParams,
    MonitorTriggerRequest,
)
from app.schemas.agent import (
    AgentTaskBase,
    AgentTaskCreate,
    AgentTaskUpdate,
    AgentTaskResponse,
    AgentTaskListParams,
)
from app.schemas.dashboard import (
    DashboardKpi,
    ChannelBreakdown,
    EngineBreakdown,
    DashboardFunnel,
    DashboardData,
    OutcomeSnapshotBase,
    OutcomeSnapshotResponse,
)

__all__ = [
    "PainPoint",
    "PersonaData",
    "CompetitorItem",
    "ScenarioBase",
    "ScenarioCreate",
    "ScenarioUpdate",
    "ScenarioResponse",
    "ScenarioListParams",
    "ChannelWeight",
    "StrategyPackBase",
    "StrategyPackCreate",
    "StrategyPackUpdate",
    "StrategyPackResponse",
    "StrategyPackListParams",
    "FactVerifyReport",
    "ComplianceReport",
    "ContentDraftBase",
    "ContentDraftCreate",
    "ContentDraftUpdate",
    "ContentDraftResponse",
    "ContentDraftListParams",
    "BulkApproveRequest",
    "ApprovalLogResponse",
    "PublishTaskBase",
    "PublishTaskCreate",
    "PublishTaskUpdate",
    "PublishTaskResponse",
    "PublishTaskListParams",
    "MonitorResultBase",
    "MonitorResultCreate",
    "MonitorResultResponse",
    "MonitorResultListParams",
    "MonitorTriggerRequest",
    "AgentTaskBase",
    "AgentTaskCreate",
    "AgentTaskUpdate",
    "AgentTaskResponse",
    "AgentTaskListParams",
    "DashboardKpi",
    "ChannelBreakdown",
    "EngineBreakdown",
    "DashboardFunnel",
    "DashboardData",
    "OutcomeSnapshotBase",
    "OutcomeSnapshotResponse",
]
